# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ARCHIVE_COMPONENT_INSTALL "OFF")
set(CPACK_BUILD_SOURCE_DIRS "/Users/enguerrand/Dev/mafia2online/Framework;/Users/enguerrand/Dev/mafia2online/Framework")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMMAND "/Applications/CMake.app/Contents/bin/cpack")
set(CPACK_COMPONENTS_ALL "runtime;dev")
set(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
set(CPACK_COMPONENT_DEV_DEPENDS "runtime")
set(CPACK_COMPONENT_DEV_DESCRIPTION "Development files for cppfs library")
set(CPACK_COMPONENT_DEV_DISPLAY_NAME "C/C++ development files")
set(CPACK_COMPONENT_INCLUDE_TOPLEVEL_DIRECTORY "OFF")
set(CPACK_COMPONENT_RUNTIME_DESCRIPTION "Runtime components for cppfs library")
set(CPACK_COMPONENT_RUNTIME_DISPLAY_NAME "cppfs library")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "all")
set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "")
set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "Cross-platform C++ file system library supporting multiple backends (Local-FS, SSH)")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "opensource@cginternals.com")
set(CPACK_DEBIAN_PACKAGE_NAME "cppfs")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
set(CPACK_DEBIAN_PACKAGE_SECTION "devel")
set(CPACK_DEBIAN_PACKAGE_VERSION "1.3.0")
set(CPACK_DEB_COMPONENT_INSTALL "OFF")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/Applications/CMake.app/Contents/share/cmake-3.21/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "Framework built using CMake")
set(CPACK_GENERATOR "TGZ")
set(CPACK_IGNORE_FILES "")
set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY "OFF")
set(CPACK_INSTALLED_DIRECTORIES "")
set(CPACK_INSTALL_CMAKE_PROJECTS "/Users/enguerrand/Dev/mafia2online/Framework;Framework;ALL;/")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "/Users/enguerrand/Dev/mafia2online/Framework/vendors/cppfs/deploy/packages/cppfs")
set(CPACK_NSIS_DISPLAY_NAME "cppfs")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
set(CPACK_NSIS_PACKAGE_NAME "cppfs")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OSX_SYSROOT "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk")
set(CPACK_OUTPUT_CONFIG_FILE "/Users/enguerrand/Dev/mafia2online/Framework/vendors/cppfs/CPackConfig-cppfs.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/Users/enguerrand/Dev/mafia2online/Framework/vendors/cppfs/README.md")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Cross-platform C++ file system library supporting multiple backends (Local-FS, SSH)")
set(CPACK_PACKAGE_FILE_NAME "cppfs-1.3.0")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "cppfs")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "cppfs")
set(CPACK_PACKAGE_NAME "cppfs")
set(CPACK_PACKAGE_RELOCATABLE "false")
set(CPACK_PACKAGE_VENDOR "CG Internals GmbH")
set(CPACK_PACKAGE_VERSION "1.3.0")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "3")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_PACKAGING_INSTALL_PREFIX "/usr/local")
set(CPACK_PATH "/Applications/CMake.app/Contents/bin")
set(CPACK_RESOURCE_FILE_LICENSE "/Users/enguerrand/Dev/mafia2online/Framework/vendors/cppfs/LICENSE")
set(CPACK_RESOURCE_FILE_README "/Users/enguerrand/Dev/mafia2online/Framework/vendors/cppfs/README.md")
set(CPACK_RESOURCE_FILE_WELCOME "/Users/enguerrand/Dev/mafia2online/Framework/vendors/cppfs/README.md")
set(CPACK_RPM_COMPONENT_INSTALL "OFF")
set(CPACK_RPM_PACKAGE_ARCHITECTURE "x86_64")
set(CPACK_RPM_PACKAGE_DESCRIPTION "")
set(CPACK_RPM_PACKAGE_GROUP "unknown")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_NAME "cppfs")
set(CPACK_RPM_PACKAGE_PROVIDES "")
set(CPACK_RPM_PACKAGE_RELEASE "1")
set(CPACK_RPM_PACKAGE_RELOCATABLE "OFF")
set(CPACK_RPM_PACKAGE_REQUIRES "")
set(CPACK_RPM_PACKAGE_SUMMARY "Cross-platform C++ file system library supporting multiple backends (Local-FS, SSH)")
set(CPACK_RPM_PACKAGE_VENDOR "CG Internals GmbH")
set(CPACK_RPM_PACKAGE_VERSION "1.3.0")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_IGNORE_FILES "")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/Users/enguerrand/Dev/mafia2online/Framework/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TOPLEVEL_TAG "")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Darwin")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Darwin")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/Users/enguerrand/Dev/mafia2online/Framework/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
