// Generated by CMake - DO NOT EDIT
#pragma once

// Current edition level (see UltralightEdition enum below)
#define ULTRALIGHT_EDITION_LEVEL 0

// Edition name string
#define ULTRALIGHT_EDITION_NAME "Free"

// Edition defines
#define ULTRALIGHT_EDITION_FREE 0
#define ULTRALIGHT_EDITION_PLUS 1
#define ULTRALIGHT_EDITION_PRO 2
#define ULTRALIGHT_EDITION_ENTERPRISE 3
#define ULTRALIGHT_EDITION_UNLIMITED 4

// Edition check macros
#define UL_EDITION(x) (ULTRALIGHT_EDITION_LEVEL == ULTRALIGHT_EDITION_##x)
#define UL_EDITION_AT_LEAST(x) (ULTRALIGHT_EDITION_LEVEL >= ULTRALIGHT_EDITION_##x)

// Maximum FPS each View can render at (0 is uncapped)
#define ULTRALIGHT_EDITION_MAX_FPS 60

// Whether or not this is an evaluation build
#define ULTRALIGHT_EVALUATION 0
