name: Build MafiaHub Services

on:
  workflow_dispatch:

jobs:
  build:
    name: Build MafiaHubServices on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            cmake_generator: "Visual Studio 17 2022"
            build_type: "Release"
          - os: ubuntu-latest
            cmake_generator: "Unix Makefiles"
            build_type: "Release"
          - os: macos-latest
            cmake_generator: "Unix Makefiles"
            build_type: "Release"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.FW_SERVICES_PAT }}
                              
      - uses: maxim-lobanov/setup-xcode@v1
        with:
            xcode-version: '16.2.0'
        if: runner.os == 'macOS'
    
      - name: Install tools on Ubuntu
        run: sudo apt-get install -y ninja-build build-essential libcurl4-openssl-dev
        if: runner.os == 'Linux'

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Set up Visual Studio shell
        if: runner.os == 'Windows'
        uses: egor-tensin/vs-shell@v2

      - name: Configure CMake (Windows)
        if: runner.os == 'Windows'
        run: |
          cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Configure CMake (Unix)
        if: runner.os != 'Windows'
        run: |
          cmake -G "${{ matrix.cmake_generator }}" -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build MafiaHubServices
        run: |
          cmake --build build --target MafiaHubServices --config ${{ matrix.build_type }}


      - name: Build MafiaHubServices
        run: |
          cmake --build build --target MafiaHubServices --config ${{ matrix.build_type }}

      - name: Upload MafiaHub Services
        uses: actions/upload-artifact@v4
        with:
          name: mafiahub-services-${{ matrix.os }}
          path: |
            ${{ github.workspace }}/code/projects/framework/src/services/lib
            ${{ github.workspace }}/code/projects/framework/src/services/services
          if-no-files-found: warn

